# Change these first
owner: Sasillo # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

assignees:
  - Sasillo

sites:
  - name: Mail
    url: https://mail.selgaraje.com
  - name: Mail SMTP
    check: "tcp-ping"
    url: mail.selgaraje.com
    port: 25
  - name: Mail SMTPs
    check: "tcp-ping"
    url: mail.selgaraje.com
    port: 465
  - name: Mail Submission
    check: "tcp-ping"
    url: mail.selgaraje.com
    port: 587
  - name: Mail IMAPs
    check: "tcp-ping"
    url: mail.selgaraje.com
    port: 993
  - name: Cloud
    url: https://cloud.selgaraje.com
  - name: Secure
    url: https://secure.selgaraje.com
  - name: Media
    url: https://media.selgaraje.com
  - name: Media MS
    check: "tcp-ping"
    url: media.selgaraje.com
    port: 32400
  - name: News
    url: https://news.selgaraje.com
  - name: Cuélebre
    url: https://cuelebre.selgaraje.com
  - name: Belenos
    url: https://belenos.selgaraje.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: SElGaraje Status
  introTitle: "SElGaraje Status"
  introMessage: ServerS Infrastructure Status
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
